DROP TABLE DOMINIO CASCADE CONSTRAINTS PURGE;
DROP TABLE TITULACION CASCADE CONSTRAINTS PURGE;
DROP TABLE PERSONAL CASCADE CONSTRAINTS PURGE;
DROP TABLE COMPANIA CASCADE CONSTRAINTS PURGE;
DROP TABLE COMUNA CASCADE CONSTRAINTS PURGE;
DROP TABLE TITULO CASCADE CONSTRAINTS PURGE;
DROP TABLE IDIOMA CASCADE CONSTRAINTS PURGE;
DROP TABLE REGION CASCADE CONSTRAINTS PURGE;
DROP TABLE ESTADO_CIVIL CASCADE CONSTRAINTS PURGE;
DROP TABLE GENERO CASCADE CONSTRAINTS PURGE;

CREATE TABLE GENERO (
    id_genero VARCHAR2(3) CONSTRAINT GENERO_ID_NN NOT NULL,
    descripcion_genero VARCHAR2(25) CONSTRAINT GENERO_DESCRIPCION_NN NOT NULL,
    CONSTRAINT GENERO_PK PRIMARY KEY (id_genero)
);

CREATE TABLE ESTADO_CIVIL (
    id_estado_civil VARCHAR2(2) CONSTRAINT ESTADO_CIVIL_ID_NN NOT NULL,
    descripcion_est_civil VARCHAR(25) CONSTRAINT ESTADO_CIVIL_DESCRIPCION_NN NOT NULL,
    CONSTRAINT ESTADO_CIVIL_PK PRIMARY KEY (id_estado_civil)
);

CREATE TABLE REGION (
    id_region NUMBER(2) GENERATED ALWAYS AS IDENTITY (
        START WITH 7
        INCREMENT BY 2
    ) CONSTRAINT REGION_ID_NN NOT NULL,
    nombre_region VARCHAR2(25) CONSTRAINT REGION_NOMBRE_NN NOT NULL,
    CONSTRAINT REGION_PK PRIMARY KEY (id_region)
);

CREATE TABLE IDIOMA (
    id_idioma NUMBER(3) GENERATED ALWAYS AS IDENTITY (
        START WITH 25
        INCREMENT BY 3
    ) CONSTRAINT IDIOMA_ID_NN NOT NULL,
    nombre_idioma VARCHAR2(30) CONSTRAINT IDIOMA_NOMBRE_NN NOT NULL,
    CONSTRAINT IDIOMA_PK PRIMARY KEY (id_idioma)
);

CREATE TABLE TITULO (
    id_titulo VARCHAR2(3) CONSTRAINT TITULO_ID_NN NOT NULL,
    descripcion_titulo VARCHAR2(60) CONSTRAINT TITULO_DESCRIPCION_NN NOT NULL,
    CONSTRAINT TITULO_PK PRIMARY KEY (id_titulo)
);

CREATE TABLE COMUNA (
    id_comuna NUMBER(5) CONSTRAINT COMUNA_ID_NN NOT NULL,
    nombre_comuna VARCHAR2(25) CONSTRAINT COMUNA_NOMBRE_NN NOT NULL,
    id_region NUMBER(2) CONSTRAINT COMUNA_REGION_NN NOT NULL,
    CONSTRAINT COMUNA_PK PRIMARY KEY (id_comuna, id_region),
    CONSTRAINT COMUNA_REGION_FK FOREIGN KEY (id_region) REFERENCES REGION (id_region)
);

CREATE TABLE COMPANIA (
    id_empresa NUMBER(2) CONSTRAINT COMPANIA_ID_NN NOT NULL,
    nombre_empresa VARCHAR2(25) CONSTRAINT COMPANIA_NOMBRE_NN NOT NULL,
    calle VARCHAR2(50) CONSTRAINT COMPANIA_CALLE_NN NOT NULL,
    numeracion NUMBER(5) CONSTRAINT COMPANIA_NUMERACION_NN NOT NULL,
    renta_promedio NUMBER(10) CONSTRAINT COMPANIA_RENTA_PROMEDIO_NN NOT NULL,
    pct_aumento NUMBER(4,3),
    id_comuna NUMBER(5) CONSTRAINT COMPANIA_COMUNA_NN NOT NULL,
    id_region NUMBER(2) CONSTRAINT COMPANIA_REGION_NN NOT NULL,
    CONSTRAINT COMPANIA_PK PRIMARY KEY (id_empresa),
    CONSTRAINT COMPANIA_NOMBRE_UN UNIQUE (nombre_empresa),
    CONSTRAINT COMPANIA_COMUNA_FK FOREIGN KEY (id_comuna, id_region) REFERENCES COMUNA (id_comuna, id_region)
);

CREATE TABLE PERSONAL (
    rut_persona NUMBER(8) CONSTRAINT PERSONAL_RUT_NN NOT NULL,
    dv_persona VARCHAR2(1) CONSTRAINT PERSONAL_DV_NN NOT NULL,
    primer_nombre VARCHAR2(25) CONSTRAINT PERSONAL_PNOMBRE_NN NOT NULL,
    segundo_nombre VARCHAR2(25),
    primer_apellido VARCHAR2(25) CONSTRAINT PERSONAL_PAPELLIDO_NN NOT NULL,
    segundo_apellido VARCHAR2(25) CONSTRAINT PERSONAL_SAPELLIDO_NN NOT NULL,
    fecha_contratacion DATE CONSTRAINT PERSONAL_FECHA_CONTRATACION_NN NOT NULL,
    fecha_nacimiento DATE CONSTRAINT PERSONAL_FECHA_NACIMIENTO_NN NOT NULL,
    email VARCHAR2(100),
    calle VARCHAR2(50) CONSTRAINT PERSONAL_CALLE_NN NOT NULL,
    numeracion NUMBER(5) CONSTRAINT PERSONAL_NUMERACION_NN NOT NULL,
    sueldo NUMBER(8) CONSTRAINT PERSONAL_SUELDO_NN NOT NULL,
    id_comuna NUMBER(5) CONSTRAINT PERSONAL_COMUNA_NN NOT NULL,
    id_region NUMBER(2) CONSTRAINT PERSONAL_REGION_NN NOT NULL,
    id_genero VARCHAR2(3),
    id_estado_civil VARCHAR2(2),
    id_empresa NUMBER(2) CONSTRAINT PERSONAL_EMPRESA_NN NOT NULL,
    encargado_rut NUMBER(8),
    CONSTRAINT PERSONAL_PK PRIMARY KEY (rut_persona),
    CONSTRAINT PERSONAL_COMUNA_FK FOREIGN KEY (id_comuna, id_region) REFERENCES COMUNA (id_comuna, id_region),
    CONSTRAINT PERSONAL_GENERO_FK FOREIGN KEY (id_genero) REFERENCES GENERO (id_genero),
    CONSTRAINT PERSONAL_ESTADO_CIVIL_FK FOREIGN KEY (id_estado_civil) REFERENCES ESTADO_CIVIL (id_estado_civil),
    CONSTRAINT PERSONAL_COMPANIA_FK FOREIGN KEY (id_empresa) REFERENCES COMPANIA (id_empresa),
    CONSTRAINT PERSONAL_PERSONAL_FK FOREIGN KEY (encargado_rut) REFERENCES PERSONAL (rut_persona)
);

CREATE TABLE TITULACION (
    id_titulo VARCHAR2(3) CONSTRAINT TITULACION_TITULO_NN NOT NULL,
    persona_rut NUMBER(8) CONSTRAINT TITULACION_PERSONA_RUT_NN NOT NULL,
    fecha_titulacion DATE CONSTRAINT TITULACION_FECHA_NN NOT NULL,
    CONSTRAINT TITULACION_PK PRIMARY KEY (id_titulo, persona_rut),
    CONSTRAINT TITULACION_TITULO_FK FOREIGN KEY (id_titulo) REFERENCES TITULO (id_titulo),
    CONSTRAINT TITULACION_PERSONAL_FK FOREIGN KEY (persona_rut) REFERENCES PERSONAL (rut_persona)
);

CREATE TABLE DOMINIO (
    id_idioma NUMBER(3) CONSTRAINT DOMINIO_IDIOMA_NN NOT NULL,
    persona_rut NUMBER(8) CONSTRAINT DOMINIO_PERSONA_NN NOT NULL,
    nivel VARCHAR2(25) CONSTRAINT DOMINIO_NIVEL_NN NOT NULL,
    CONSTRAINT DOMINIO_PK PRIMARY KEY (id_idioma, persona_rut),
    CONSTRAINT DOMINIO_IDIOMA_FK FOREIGN KEY (id_idioma) REFERENCES IDIOMA (id_idioma),
    CONSTRAINT DOMINIO_PERSONAL_FK FOREIGN KEY (persona_rut) REFERENCES PERSONAL (rut_persona)
);

ALTER TABLE PERSONAL ADD CONSTRAINT PERSONAL_EMAIL_UN UNIQUE (email);
ALTER TABLE PERSONAL ADD CONSTRAINT PERSONAL_DV_CK CHECK (dv_persona IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K'));
ALTER TABLE PERSONAL ADD CONSTRAINT PERSONAL_SUELDO_CK CHECK (sueldo >= 450000);

CREATE SEQUENCE SEQ_COMUNA
    START WITH 1101
    INCREMENT BY 6;

CREATE SEQUENCE SEQ_COMPANIA
    START WITH 10
    INCREMENT BY 5;

INSERT INTO REGION (nombre_region) VALUES ('ARICA Y PARINACOTA');
INSERT INTO REGION (nombre_region) VALUES ('METROPOLITANA');
INSERT INTO REGION (nombre_region) VALUES ('LA ARAUCANIA');

INSERT INTO IDIOMA (nombre_idioma) VALUES ('Ingles');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Chino');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Aleman');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Espanol');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Frances');

INSERT INTO COMUNA VALUES (SEQ_COMUNA.NEXTVAL, 'Arica', 7);
INSERT INTO COMUNA VALUES (SEQ_COMUNA.NEXTVAL, 'Santiago', 9);
INSERT INTO COMUNA VALUES (SEQ_COMUNA.NEXTVAL, 'Temuco', 11);

INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'CCyRojas', 'Amapolas', 506, 1857000, 0.5, 1101, 7);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'SenTTy', 'Los Alamos', 3490, 897000, 0.025, 1101, 7);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'Praxia LTDA', 'Las Camelias', 11098, 2157000, 0.035, 1107, 9);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'TIC spa', 'FLORES S.A.', 4357, 857000, NULL, 1107, 9);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'SANTANA LTDA', 'AVDA VIC. MACKENA', 106, 757000, 0.015, 1101, 7);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'FLORES Y ASOCIADOS', 'PEDRO LATORRE', 557, 589000, 0.015, 1107, 9);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'J.A. HOFFMAN', 'LATINA D.32', 509, 1857000, 0.025, 1113, 11);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'CAGLIARI D.', 'ALAMEDA', 206, 1857000, NULL, 1107, 9);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'Rojas HNOS LTDA', 'SUCRE', 106, 957000, 0.005, 1113, 11);
INSERT INTO COMPANIA VALUES (SEQ_COMPANIA.NEXTVAL, 'FRIENDS P. S.A', 'SUECIA', 506, 857000, 0.015, 1113, 11);


SELECT
    nombre_empresa AS "Nombre Empresa",
    calle || ' ' || numeracion AS "Dirección",
    renta_promedio AS "Renta Promedio",
    renta_promedio * (1 + pct_aumento) AS "Simulación de Renta"
FROM COMPANIA
ORDER BY renta_promedio DESC, nombre_empresa ASC;


SELECT
    id_empresa AS "Codigo",
    nombre_empresa AS "Empresa",
    renta_promedio AS "Prom Renta Actual",
    pct_aumento + 0.15 AS "Pct Aumentado en 15%",
    renta_promedio * (pct_aumento + 0.15) AS "Renta Aumentada"
FROM COMPANIA
ORDER BY renta_promedio ASC, nombre_empresa DESC;